name: 'Deploy GCP Bucket via Terraform'
on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      bucketName:
        description: 'Name of the bucket'
        required: true
        type: string
      locationType:
        description: 'Location Type'
        required: true
        type: string
      storageClass:
        description: 'Storage Class Type'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to GCP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }} # Inject the GCP secret
        run: |
          echo "$GOOGLE_CREDENTIALS" > "${HOME}/gcp_keystore.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp_keystore.json"

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
